__version__ = "0.1.0"
import os, sys

from .patterns_cs_DAYNAME import patterns_cs_DAYNAME
from .patterns_cy_DAYNAME import patterns_cy_DAYNAME
from .patterns_de_DAYNAME import patterns_de_DAYNAME
from .patterns_en_DAYNAME import patterns_en_DAYNAME
from .patterns_es_DAYNAME import patterns_es_DAYNAME
from .patterns_fr_DAYNAME import patterns_fr_DAYNAME
from .patterns_it_DAYNAME import patterns_it_DAYNAME
from .patterns_nl_DAYNAME import patterns_nl_DAYNAME
from .patterns_no_DAYNAME import patterns_no_DAYNAME
from .patterns_sv_DAYNAME import patterns_sv_DAYNAME

from .patterns_cs_MONTHNAME import patterns_cs_MONTHNAME
from .patterns_de_MONTHNAME import patterns_de_MONTHNAME
from .patterns_en_MONTHNAME import patterns_en_MONTHNAME
from .patterns_es_MONTHNAME import patterns_es_MONTHNAME
from .patterns_fr_MONTHNAME import patterns_fr_MONTHNAME
from .patterns_it_MONTHNAME import patterns_it_MONTHNAME
from .patterns_nl_MONTHNAME import patterns_nl_MONTHNAME
from .patterns_no_MONTHNAME import patterns_no_MONTHNAME
from .patterns_sv_MONTHNAME import patterns_sv_MONTHNAME

from .patterns_cs_SEASONNAME import patterns_cs_SEASONNAME
from .patterns_de_SEASONNAME import patterns_de_SEASONNAME
from .patterns_en_SEASONNAME import patterns_en_SEASONNAME
from .patterns_es_SEASONNAME import patterns_es_SEASONNAME
from .patterns_fr_SEASONNAME import patterns_fr_SEASONNAME
from .patterns_it_SEASONNAME import patterns_it_SEASONNAME
from .patterns_nl_SEASONNAME import patterns_nl_SEASONNAME
from .patterns_no_SEASONNAME import patterns_no_SEASONNAME
from .patterns_sv_SEASONNAME import patterns_sv_SEASONNAME

from .patterns_cs_ORDINAL import patterns_cs_ORDINAL
from .patterns_de_ORDINAL import patterns_de_ORDINAL
from .patterns_en_ORDINAL import patterns_en_ORDINAL
from .patterns_es_ORDINAL import patterns_es_ORDINAL
from .patterns_fr_ORDINAL import patterns_fr_ORDINAL
from .patterns_it_ORDINAL import patterns_it_ORDINAL
from .patterns_nl_ORDINAL import patterns_nl_ORDINAL
from .patterns_no_ORDINAL import patterns_no_ORDINAL
from .patterns_sv_ORDINAL import patterns_sv_ORDINAL

from .patterns_cs_DATEPREFIX import patterns_cs_DATEPREFIX
from .patterns_de_DATEPREFIX import patterns_de_DATEPREFIX
from .patterns_en_DATEPREFIX import patterns_en_DATEPREFIX
from .patterns_es_DATEPREFIX import patterns_es_DATEPREFIX
from .patterns_fr_DATEPREFIX import patterns_fr_DATEPREFIX
from .patterns_it_DATEPREFIX import patterns_it_DATEPREFIX
from .patterns_nl_DATEPREFIX import patterns_nl_DATEPREFIX
from .patterns_no_DATEPREFIX import patterns_no_DATEPREFIX
from .patterns_sv_DATEPREFIX import patterns_sv_DATEPREFIX

from .patterns_cs_DATESUFFIX import patterns_cs_DATESUFFIX
from .patterns_de_DATESUFFIX import patterns_de_DATESUFFIX
from .patterns_en_DATESUFFIX import patterns_en_DATESUFFIX
from .patterns_es_DATESUFFIX import patterns_es_DATESUFFIX
from .patterns_fr_DATESUFFIX import patterns_fr_DATESUFFIX
from .patterns_it_DATESUFFIX import patterns_it_DATESUFFIX
from .patterns_nl_DATESUFFIX import patterns_nl_DATESUFFIX
from .patterns_no_DATESUFFIX import patterns_no_DATESUFFIX
from .patterns_sv_DATESUFFIX import patterns_sv_DATESUFFIX

from .patterns_cs_DATESEPARATOR import patterns_cs_DATESEPARATOR
from .patterns_de_DATESEPARATOR import patterns_de_DATESEPARATOR
from .patterns_en_DATESEPARATOR import patterns_en_DATESEPARATOR
from .patterns_es_DATESEPARATOR import patterns_es_DATESEPARATOR
from .patterns_fr_DATESEPARATOR import patterns_fr_DATESEPARATOR
from .patterns_it_DATESEPARATOR import patterns_it_DATESEPARATOR
from .patterns_nl_DATESEPARATOR import patterns_nl_DATESEPARATOR
from .patterns_no_DATESEPARATOR import patterns_no_DATESEPARATOR
from .patterns_sv_DATESEPARATOR import patterns_sv_DATESEPARATOR

from .patterns_cs_YEARSPAN import patterns_cs_YEARSPAN
from .patterns_de_YEARSPAN import patterns_de_YEARSPAN
from .patterns_en_YEARSPAN import patterns_en_YEARSPAN
from .patterns_es_YEARSPAN import patterns_es_YEARSPAN
from .patterns_fr_YEARSPAN import patterns_fr_YEARSPAN
from .patterns_it_YEARSPAN import patterns_it_YEARSPAN
from .patterns_nl_YEARSPAN import patterns_nl_YEARSPAN
from .patterns_no_YEARSPAN import patterns_no_YEARSPAN
from .patterns_sv_YEARSPAN import patterns_sv_YEARSPAN

# experimental...
from .patterns_en_NEGATION import patterns_en_NEGATION
from .patterns_en_ATTRIBUTE_RULES import patterns_en_ATTRIBUTE_RULES

# superseded by PeriodoRuler
from .patterns_no_PERIOD import patterns_no_PERIOD
from .patterns_sv_PERIOD import patterns_sv_PERIOD

#sys.path.append(os.path.dirname(os.path.realpath(__file__)))
