---
# Commands to run on initial workspace startup
tasks:
    - init: 
        pip install --upgrade pip;
        pip install -r requirements.txt;        
        python -m spacy download de_core_news_sm;
        python -m spacy download en_core_web_sm;
        python -m spacy download es_core_news_sm;
        python -m spacy download fr_core_news_sm;
        python -m spacy download it_core_news_sm; 
        python -m spacy download nl_core_news_sm;
        python -m spacy download nb_core_news_sm; 
        python -m spacy download sv_core_news_sm;                   
#- command:
#pip install --upgrade pip;
#pip install -r "requirements.txt";
#python -m spacy download de_core_news_sm;
#python -m spacy download en_core_web_sm;
#python -m spacy download es_core_news_sm;
#python -m spacy download fr_core_news_sm;
#python -m spacy download it_core_news_sm; 
#python -m spacy download nl_core_news_sm;
#python -m spacy download nb_core_news_sm; 
#python -m spacy download sv_core_news_sm;      
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
   - port: 8080
     onOpen: open-preview
   - port: 8888
     onOpen: open-browser

# Install necessary packages
image:
    file: .gitpod.dockerfile

vscode:
    extensions:
        - ms-toolsai.jupyter   
        - ms-python.python     
        - ms-toolsai.jupyter-renderers
        - ms-toolsai.jupyter-keymap
