# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
    #- init: | 
        #pip install -r "requirements.txt";
        #python -m spacy download de_core_news_sm;
        #python -m spacy download en_core_web_sm;
        #python -m spacy download es_core_news_sm;
        #python -m spacy download fr_core_news_sm;
        #python -m spacy download it_core_news_sm; 
        #python -m spacy download nl_core_news_sm;
        #python -m spacy download nb_core_news_sm; 
        #python -m spacy download sv_core_news_sm;                   
    - command:
        pip install -r "requirements.txt";
        python -m spacy download de_core_news_sm;
        python -m spacy download en_core_web_sm;
        python -m spacy download es_core_news_sm;
        python -m spacy download fr_core_news_sm;
        python -m spacy download it_core_news_sm; 
        python -m spacy download nl_core_news_sm;
        python -m spacy download nb_core_news_sm; 
        python -m spacy download sv_core_news_sm;      
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
    - port: 9000-9099
      onOpen: ignore

# Install necessary packages
image:
    file: .gitpod.dockerfile

vscode:
    extensions:
        - ms-toolsai.jupyter