x = [
{'id': 'http://tempuri/supplementary/pleistocene', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['PLEISTOCENE', 'Pleistocene', 'pleistocene']}}]},
{'id': 'http://tempuri/supplementary/holocene', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Holocene', 'holocene', 'HOLOCENE']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsts5m', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Late', 'late', 'LATE']}}, {'LEMMA': {'IN': ['Paleolithic', 'paleolithic', 'PALEOLITHIC']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsts5m', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Late', 'late', 'LATE']}}, {'LEMMA': {'IN': ['PALAEOLITHIC', 'palaeolithic', 'Palaeolithic']}}]},
{'id': 'http://tempuri/supplementary/saxon', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['SAXON', 'Saxon', 'saxon']}}]},
{'id': 'http://tempuri/supplementary/anglo-saxon', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['anglo', 'ANGLO', 'Anglo']}}, {'LEMMA': {'IN': ['SAXON', 'Saxon', 'saxon']}}]},
{'id': 'http://tempuri/supplementary/anglo-saxon', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['anglo', 'ANGLO', 'Anglo']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['SAXON', 'Saxon', 'saxon']}}]},
{'id': 'http://tempuri/supplementary/romano-british', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['ROMANO', 'romano', 'Romano']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['british', 'BRITISH', 'British']}}]},
{'id': 'http://tempuri/supplementary/romano-british', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['ROMANO', 'romano', 'Romano']}}, {'LEMMA': {'IN': ['british', 'BRITISH', 'British']}}]},
{'id': 'http://tempuri/supplementary/post-medieval', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['POST', 'Post', 'post']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['Medieval', 'medieval', 'MEDIEVAL']}}]},
{'id': 'http://tempuri/supplementary/post-medieval', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['POST', 'Post', 'post']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['mediaeval', 'Mediaeval', 'MEDIAEVAL']}}]},
{'id': 'http://tempuri/supplementary/viking', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['VIKE', 'viking', 'Vike', 'VIKING', 'vike', 'Viking']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/70403', 'label': 'MONUMENT', 'pattern': [{'LEMMA': {'IN': ['POST', 'Post', 'post']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['hole', 'HOLE', 'Hole']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/70403', 'label': 'MONUMENT', 'pattern': [{'LEMMA': {'IN': ['posthole', 'Posthole', 'POSTHOLE']}}]},
{'id': 'http://tempuri/supplementary/roundhouse', 'label': 'MONUMENT', 'pattern': [{'LEMMA': {'IN': ['ROUNDHOUSE', 'roundhouse', 'Roundhouse']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/70267', 'label': 'MONUMENT', 'pattern': [{'LEMMA': {'IN': ['hollow', 'Hollow', 'HOLLOW']}}, {'LOWER': '-'}, {'LOWER': 'way'}]},
{'id': 'http://tempuri/supplementary/flint', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['flint', 'Flint', 'FLINT']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/96399', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['BLADELET', 'bladelet', 'Bladelet']}}]},
{'id': 'http://tempuri/supplementary/pottery', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['Pottery', 'pottery', 'POTTERY']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/97042', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['LOOM', 'Loom', 'loom']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['WEIGHT', 'Weight', 'weight']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/97042', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['LOOM', 'Loom', 'loom']}}, {'LEMMA': {'IN': ['WEIGHT', 'Weight', 'weight']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/96961', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['QUERNSTONE', 'Quernstone', 'quernstone']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/96961', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['QUERN', 'quern', 'Quern']}}, {'LEMMA': {'IN': ['STONE', 'Stone', 'stone']}}]},
]