x = [
{'id': 'http://tempuri/supplementary/pleistocene', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['PLEISTOCENE', 'Pleistocene', 'pleistocene']}}]},
{'id': 'http://tempuri/supplementary/holocene', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['holocene', 'HOLOCENE', 'Holocene']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsts5m', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['upper', 'UPPER', 'Upper']}}, {'LEMMA': {'IN': ['paleolithic', 'PALEOLITHIC', 'Paleolithic']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsts5m', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['LATE', 'late', 'Late']}}, {'LEMMA': {'IN': ['paleolithic', 'PALEOLITHIC', 'Paleolithic']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsts5m', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['LATE', 'late', 'Late']}}, {'LEMMA': {'IN': ['Palaeolithic', 'palaeolithic', 'PALAEOLITHIC']}}]},
{'id': 'http://tempuri/supplementary/saxon', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Saxon', 'SAXON', 'saxon']}}]},
{'id': 'http://tempuri/supplementary/late-saxon', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['LATE', 'late', 'Late']}}, {'LEMMA': {'IN': ['Saxon', 'SAXON', 'saxon']}}]},
{'id': 'http://tempuri/supplementary/anglo-saxon', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['anglo', 'Anglo', 'ANGLO']}}, {'LEMMA': {'IN': ['Saxon', 'SAXON', 'saxon']}}]},
{'id': 'http://tempuri/supplementary/anglo-saxon', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['anglo', 'Anglo', 'ANGLO']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['Saxon', 'SAXON', 'saxon']}}]},
{'id': 'http://tempuri/supplementary/romano-british', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Romano', 'romano', 'ROMANO']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['BRITISH', 'British', 'british']}}]},
{'id': 'http://tempuri/supplementary/romano-british', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Romano', 'romano', 'ROMANO']}}, {'LEMMA': {'IN': ['BRITISH', 'British', 'british']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsctsj', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Post', 'POST', 'post']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['Medieval', 'medieval', 'MEDIEVAL']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsctsj', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Post', 'POST', 'post']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['MEDIAEVAL', 'mediaeval', 'Mediaeval']}}]},
{'id': 'http://tempuri/supplementary/viking', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['vike', 'VIKING', 'VIKE', 'viking', 'Viking', 'Vike']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/70403', 'label': 'MONUMENT', 'pattern': [{'LEMMA': {'IN': ['Post', 'POST', 'post']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['hole', 'HOLE', 'Hole']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/70403', 'label': 'MONUMENT', 'pattern': [{'LEMMA': {'IN': ['Posthole', 'POSTHOLE', 'posthole']}}]},
{'id': 'http://tempuri/supplementary/roundhouse', 'label': 'MONUMENT', 'pattern': [{'LEMMA': {'IN': ['roundhouse', 'Roundhouse', 'ROUNDHOUSE']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/70267', 'label': 'MONUMENT', 'pattern': [{'LEMMA': {'IN': ['Hollow', 'hollow', 'HOLLOW']}}, {'LOWER': '-'}, {'LOWER': 'way'}]},
{'id': 'http://tempuri/supplementary/flint', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['FLINT', 'Flint', 'flint']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/96399', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['bladelet', 'BLADELET', 'Bladelet']}}]},
{'id': 'http://tempuri/supplementary/pottery', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['pottery', 'POTTERY', 'Pottery']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/97042', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['loom', 'Loom', 'LOOM']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['weight', 'Weight', 'WEIGHT']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/97042', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['loom', 'Loom', 'LOOM']}}, {'LEMMA': {'IN': ['weight', 'Weight', 'WEIGHT']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/96961', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['QUERNSTONE', 'Quernstone', 'quernstone']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/96961', 'label': 'OBJECT', 'pattern': [{'LEMMA': {'IN': ['QUERN', 'quern', 'Quern']}}, {'LEMMA': {'IN': ['stone', 'STONE', 'Stone']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/142915', 'label': 'OBJECT', 'pattern': [{'POS': 'ADJ', 'LOWER': 'alluvial'}, {'POS': 'NOUN'}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/142915', 'label': 'OBJECT', 'pattern': [{'POS': 'ADJ'}, {'LOWER': 'alluvium'}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/142920', 'label': 'OBJECT', 'pattern': [{'POS': 'ADJ', 'LOWER': 'colluvial'}, {'POS': 'NOUN'}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/142920', 'label': 'OBJECT', 'pattern': [{'POS': 'ADJ'}, {'LOWER': 'colluvium'}]},
]