x = [
{'id': 'http://tempuri/supplementary/pleistocene', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['pleistocene', 'PLEISTOCENE', 'Pleistocene']}}]},
{'id': 'http://tempuri/supplementary/holocene', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['holocene', 'Holocene', 'HOLOCENE']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsts5m', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Upper', 'UPPER', 'upper']}}, {'LEMMA': {'IN': ['PALAEOLITHIC', 'Palaeolithic', 'palaeolithic']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsts5m', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Late', 'late', 'LATE']}}, {'LEMMA': {'IN': ['PALAEOLITHIC', 'Palaeolithic', 'palaeolithic']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsts5m', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Late', 'late', 'LATE']}}, {'LEMMA': {'IN': ['PALAEOLITHIC', 'Palaeolithic', 'palaeolithic']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsts5m', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['later', 'Later', 'LATER']}}, {'LEMMA': {'IN': ['PALAEOLITHIC', 'Palaeolithic', 'palaeolithic']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsts5m', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['later', 'Later', 'LATER']}}, {'LEMMA': {'IN': ['PALAEOLITHIC', 'Palaeolithic', 'palaeolithic']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dscmjf', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['later', 'Later', 'LATER']}}, {'LEMMA': {'IN': ['mesolithic', 'Mesolithic', 'MESOLITHIC']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9ds4hjq', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['later', 'Later', 'LATER']}}, {'LEMMA': {'IN': ['Neolithic', 'neolithic', 'NEOLITHIC']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9ds8p8k', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['later', 'Later', 'LATER']}}, {'LEMMA': {'IN': ['BRONZE', 'Bronze', 'bronze']}}, {'LOWER': 'age'}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9ds8p8k', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['later', 'Later', 'LATER']}}, {'LEMMA': {'IN': ['IRON', 'iron', 'Iron']}}, {'LOWER': 'age'}]},
{'id': 'http://tempuri/supplementary/beaker', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Beaker', 'beaker', 'BEAKER']}}]},
{'id': 'http://tempuri/supplementary/early-beaker', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['EARLY', 'Early', 'early']}}, {'LEMMA': {'IN': ['Beaker', 'beaker', 'BEAKER']}}]},
{'id': 'http://tempuri/supplementary/late-beaker', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Late', 'late', 'LATE']}}, {'LEMMA': {'IN': ['Beaker', 'beaker', 'BEAKER']}}]},
{'id': 'http://tempuri/supplementary/late-beaker', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['later', 'Later', 'LATER']}}, {'LEMMA': {'IN': ['Beaker', 'beaker', 'BEAKER']}}]},
{'id': 'http://tempuri/supplementary/saxon', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['saxon', 'Saxon', 'SAXON']}}]},
{'id': 'http://tempuri/supplementary/saxon', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Late', 'late', 'LATE']}}, {'LEMMA': {'IN': ['saxon', 'Saxon', 'SAXON']}}]},
{'id': 'http://tempuri/supplementary/saxon', 'label': 'PERIOD', 'pattern': [{'LOWER': 'anglo'}, {'OP': '?', 'ORTH': '-'}, {'LOWER': 'saxon'}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9ds9nsj', 'label': 'PERIOD', 'pattern': [{'LOWER': 'romano'}, {'OP': '?', 'ORTH': '-'}, {'LOWER': 'british'}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsmf3f', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['EARLY', 'Early', 'early']}}, {'LEMMA': {'IN': ['medieval', 'MEDIEVAL', 'Medieval']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dscbkd', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['medieval', 'MEDIEVAL', 'Medieval']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dscbkd', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['HIGH', 'high', 'High']}}, {'LEMMA': {'IN': ['medieval', 'MEDIEVAL', 'Medieval']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dscbkd', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['HIGH', 'high', 'High']}}, {'LEMMA': {'IN': ['medieval', 'MEDIEVAL', 'Medieval']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dscbkd', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Late', 'late', 'LATE']}}, {'LEMMA': {'IN': ['medieval', 'MEDIEVAL', 'Medieval']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dscbkd', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Late', 'late', 'LATE']}}, {'LEMMA': {'IN': ['medieval', 'MEDIEVAL', 'Medieval']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsctsj', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Post', 'POST', 'post']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['medieval', 'MEDIEVAL', 'Medieval']}}]},
{'id': 'http://n2t.net/ark:/99152/p0kh9dsctsj', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['Post', 'POST', 'post']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['medieval', 'MEDIEVAL', 'Medieval']}}]},
{'id': 'http://tempuri/supplementary/viking', 'label': 'PERIOD', 'pattern': [{'LEMMA': {'IN': ['VIKING', 'vike', 'VIKE', 'viking', 'Vike', 'Viking']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/96399', 'label': 'FISH_OBJECT', 'pattern': [{'LEMMA': {'IN': ['BLADELET', 'bladelet', 'Bladelet']}}]},
{'id': 'http://tempuri/supplementary/borehole', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['Borehole', 'borehole', 'BOREHOLE']}}]},
{'id': 'http://tempuri/supplementary/borehole', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['BORE', 'bore', 'Bore']}}, {'LEMMA': {'IN': ['HOLE', 'hole', 'Hole']}}]},
{'id': 'http://tempuri/supplementary/borehole', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['BORE', 'bore', 'Bore']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['HOLE', 'hole', 'Hole']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/70462', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['Channel', 'channel', 'CHANNEL']}}]},
{'id': '/purl.org/heritagedata/schemes/eh_tmt2/concepts/78156', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['COBBLE', 'COBBLES', 'cobbles', 'cobble', 'Cobbles', 'Cobble']}}]},
{'id': 'http://tempuri/supplementary/cofferdam', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['COFFERDAM', 'Cofferdam', 'cofferdam']}}]},
{'id': 'http://tempuri/supplementary/cofferdam', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['coffer', 'Coffer', 'COFFER']}}, {'LOWER': 'dam'}]},
{'id': 'http://tempuri/supplementary/cofferdam', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['coffer', 'Coffer', 'COFFER']}}, {'LOWER': '-'}, {'LOWER': 'dam'}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/71132', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['CORRAL', 'corral', 'Corral']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/142911', 'label': 'FISH_OBJECT', 'pattern': [{'LEMMA': {'IN': ['DEPOSITION', 'Deposition', 'deposition']}}]},
{'id': 'http://tempuri/supplementary/flint', 'label': 'FISH_OBJECT', 'pattern': [{'LEMMA': {'IN': ['flint', 'FLINT', 'Flint']}}]},
{'id': 'http://tempuri/supplementary/floodplain', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['FLOODPLAIN', 'Floodplain', 'floodplain']}}]},
{'id': 'http://tempuri/supplementary/floodplain', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['Flood', 'flood', 'FLOOD']}}, {'LEMMA': {'IN': ['plain', 'Plain', 'PLAIN']}}]},
{'id': 'http://tempuri/supplementary/floodplain', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['Flood', 'flood', 'FLOOD']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['plain', 'Plain', 'PLAIN']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/70267', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['HOLLOW', 'Hollow', 'hollow']}}, {'LOWER': '-'}, {'LOWER': 'way'}]},
{'id': 'http://tempuri/supplementary/launchchamber', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['launch', 'Launch', 'LAUNCH']}}, {'LEMMA': {'IN': ['chamber', 'Chamber', 'CHAMBER']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/97042', 'label': 'FISH_OBJECT', 'pattern': [{'LEMMA': {'IN': ['Loom', 'LOOM', 'loom']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['Weight', 'weight', 'WEIGHT']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/97042', 'label': 'FISH_OBJECT', 'pattern': [{'LEMMA': {'IN': ['Loom', 'LOOM', 'loom']}}, {'LEMMA': {'IN': ['Weight', 'weight', 'WEIGHT']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/70403', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['Post', 'POST', 'post']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['HOLE', 'hole', 'Hole']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/70403', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['posthole', 'POSTHOLE', 'Posthole']}}]},
{'id': 'http://tempuri/supplementary/pottery', 'label': 'FISH_OBJECT', 'pattern': [{'LEMMA': {'IN': ['pottery', 'POTTERY', 'Pottery']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/96961', 'label': 'FISH_OBJECT', 'pattern': [{'LEMMA': {'IN': ['QUERNSTONE', 'quernstone', 'Quernstone']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/96961', 'label': 'FISH_OBJECT', 'pattern': [{'LEMMA': {'IN': ['quern', 'Quern', 'QUERN']}}, {'LEMMA': {'IN': ['Stone', 'STONE', 'stone']}}]},
{'id': 'http://tempuri/supplementary/roundhouse', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['roundhouse', 'ROUNDHOUSE', 'Roundhouse']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/86499', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['SCATTER', 'scatter', 'Scatter']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/94083', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['Stakehole', 'STAKEHOLE', 'stakehole']}}]},
{'id': 'http://purl.org/heritagedata/schemes/eh_tmt2/concepts/94083', 'label': 'FISH_MONUMENT', 'pattern': [{'LEMMA': {'IN': ['stake', 'Stake', 'STAKE']}}, {'LOWER': '-'}, {'LEMMA': {'IN': ['HOLE', 'hole', 'Hole']}}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/142915', 'label': 'FISH_OBJECT', 'pattern': [{'POS': 'ADJ', 'LOWER': 'alluvial'}, {'POS': 'NOUN'}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/142915', 'label': 'FISH_OBJECT', 'pattern': [{'POS': 'ADJ'}, {'LOWER': 'alluvium'}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/142920', 'label': 'FISH_OBJECT', 'pattern': [{'POS': 'ADJ', 'LOWER': 'colluvial'}, {'POS': 'NOUN'}]},
{'id': 'http://purl.org/heritagedata/schemes/mda_obj/concepts/142920', 'label': 'FISH_OBJECT', 'pattern': [{'POS': 'ADJ'}, {'LOWER': 'colluvium'}]},
]