patterns_en_SIGNIFICANCE = [
    [{ "LOWER": { "REGEX": "^biostratigraph(ic|y)$" }}],
    [{ "LOWER": { "REGEX": "^calibrat(ed|ion)$" }}],
    [{ "LOWER": { "REGEX": "^carbon(14)?$" }}],
    [{ "OP": "?", "LOWER": "carbon" }, { "LOWER": { "REGEX": "^dat(es?|ing|ed)$" }}],            
    [{ "LOWER": "c14" }],
    #[{ "LOWER": "compelling" }],##
    #[{ "LOWER": "conclusions" }],##
    #[{ "LOWER": "considerable" }],##
    [{ "LOWER": { "REGEX": "^dendro(chronolog(y|ical))?$" }}],
    [{ "LOWER": "enormous" }],
    [{ "LOWER": "evidence" }],
    [{ "LOWER": "exceptional" }],
    [{ "LOWER": "extraordinary" }],
    [{ "LOWER": "important" }],
    [{ "LOWER": "interesting" }],
    [{ "LOWER": { "REGEX": "^notabl[ey]$" }}],##
    [{ "LOWER": "noteworthy" }],
    [{ "LOWER": "radiocarbon" }],
    [{ "LOWER": "radio" }, {"OP": "?", "ORTH": "-"}, { "LOWER": "carbon" }, { "OP": "?", "LOWER": { "REGEX": "^dat(es?|ing|ed)$" }}],
    [{ "LOWER": "rare" }],
    [{ "LOWER": "remarkable" }],
    [{ "LOWER": "salient" }],
    [{ "LOWER": "significant" }],
    [{ "LOWER": "spectacular" }],
    [{ "LOWER": "spectrometry" }],
    [{ "LOWER": "stratigraphy" }],
    [{ "LOWER": "surprising" }],
    [{ "LOWER": "tree" }, { "LOWER": "ring"}],     
    [{ "LOWER": "unexpected" }],    
    [{ "LOWER": "unique" }],
    [{ "LOWER": "unusual" }],
    [{ "LOWER": "vital" }],                       
    #[{"OP": "?", "LOWER": {"REGEX": "(quite|exceptionally|extraordinarily|particularly|highly|most|very|extremely|nationally)"}},  {"LOWER": { "REGEX": "(significant|major|important)"}}, {"OP": "?", "LOWER": {"REGEX": "(discover(y|ies)|findings?)"}}],
    #[{"OP": "?", "LOWER": {"REGEX": "(obvious|extraordinary|exceptional|particular|undoubted|great|major)"}}, { "LOWER": {"REGEX": "(significance|importance)"}}],
    #[{"LOWER": "earliest"}, {"LOWER": "dated"}],
    #[{"OP": "?", "LOWER":  {"REGEX": "(important|excellent)"}}, {"LOWER": {"REGEX": "insights?"}}],
    #[{"LOWER": "exceptionally"}, {"LOWER": "rich"}],
    #[{"LOWER": "extraordinary"}, {"LOWER": "assemblage"}],
    #[{"LOWER": "enormous"}, {"LOWER": "feature"}],
    #[{"OP": "?", "LOWER": "particularly"}, {"LOWER": "interesting"}],
    #[{"LOWER": "evidence"}, {"LOWER": "highlights"}],
    #[{"LOWER": "assemblage"}, {"LOWER": "is"}, {"LOWER": "important"}],
    #[{"LOWER": "important"}, {"OP": "?", "LOWER": {"REGEX": "(assemblage|find(ing)?|evidence|discovery)"}}],
    #[{"LOWER": "results"}, {"LOWER": "of"}, {"LOWER": "this"}, {"LOWER": {"REGEX": "(investigation|excavation)"}}],
    #[{"LOWER": "principle"}, {"LOWER": {"REGEX": "(aims|features?)"}}],
    #[{"LOWER": "principal"}, {"LOWER": {"REGEX": "(aims|features?)"}}],
    #[{"OP": "?", "LOWER": "more"}, {"LOWER": "substantial"}, {"OP": "?", "LOWER": "activity"}],
    #[{"LOWER": {"REGEX": "(main|major)"}}, {"LOWER": "phase"}],
    #[{"LOWER": "strongly"}, {"LOWER": {"REGEX": "(hints|suggests)"}}],
    #[{"LOWER": "first"}, {"LOWER": "record"}, {"LOWER": "of"}],
    #[{"LOWER": "not"}, {"LOWER": "typically"}, {"LOWER": "found"}],
    #[{"LOWER": "unique"}, {"LOWER": "in"}, {"LOWER": "britain"}],
    #[{"LOWER": "radio"}, {"OP": "?", "ORTH": "-"}, {"LOWER": "carbon"}, {"OP": "?", "LOWER": {"REGEX": "dat(ing|ed|e)"}}],
    #[{"LOWER": "most"}, {"LOWER": {"REGEX": "important(ly)?"}}],
    #[{"LOWER": {"REGEX": "strong(er)?"}}, {"LOWER": "evidence"}, {"OP": "?", "LOWER": {"REGEX": "(for|of)"}}],
    #[{"LOWER": "rare"}, {"LOWER": "example"}, {"OP": "?", "LOWER": "of"}],
    #[{"LOWER": {"REGEX": "(strong(er|ly)?|considerable|important|plentiful)"}}, {"LOWER": "evidence"}],           
]